config/routes.rb
Kursaktrue::Application.routes.draw do

  get "static/index"

  get "admins/index"

  get "admins/new"

  get "admins/show"

  get "admins/edit"
 
 get "admins/download"

  resources :private_realty_demands

  resources :private_realty_proposes

  resources :commerce_demands

  resources :commerce_proposes

  resources :demands

  resources :proposes

  root :to => 'static#index'

  devise_for :admins, :path_prefix => 'd'
  resources :admins

as :admin do
  
  get 'signin' => 'devise/sessions#new', :as => :new_admin_session
  post 'signin' => 'devise/sessions#create', :as => :admin_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session

end

end

app/views/admins/_form.html.erb
<%= form_for @admin, :html => { :class => 'form-horizontal' } do |f| %>

<%@levels=[1,2,3,4]%>

<dl class="dl-horizontal">



  
  <dt><strong>Логін:</strong></dt>
  <dd><strong><%= @admin.email %></strong></dd>
  <dd><%= f.text_field :email, :class => 'text_field' %></dd>
  </br></br>

  <dt><strong>Пароль:</strong></dt>
  <dd><%= f.password_field :password, :class => 'text_field' %></dd>
  </br>  

  <dt><strong>Підтвердження паролю:</strong></dt>
 
  <dd><%= f.password_field :password_confirmation, :class => 'text_field' %></dd></br>

  <dt><strong>Рівень користувача:</strong></dt>
 
  <dd><%= f.select :level,options_for_select( [@admin.level]+@levels), :class=>"span1"%></dd>
  </br>


</dl>




 <div class="form-actions", style="background:#ffed73">
    <%= f.submit :Оновити, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("Відмінити")),
                admins_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admins/_hlam.html.erb
<body style="background:#ffed73" >
<div   id="panel" class="span12"  style=" position:fixed;background:#ff8940;" >

 <%= render 'devise/menu/login_items' %>
<%= link_to "Повернутися на головну сторінку", :controller => "static", :action => "index" %>
  <h6 >Користувачі</h6>





</div>
</br></br></br></br></br></br></br></br></br></br></br>


<div class="span12">
<table id="sort" class="table table-condensed" >
  <thead ></br></br>
<%= link_to t('.new', :default => t("Новий користувач")), new_admin_path, :class => 'btn btn-success', :style=>"background:#3d9200" %>
    <tr >
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Логін користувача</th>
      <th>Дата реєстрації</th>

      <th>Дії</th>
	
    </tr>




      
  </thead>

  <tbody >
    
    <% @admins.each do |admin| %>
      <tr >


        <td><%= link_to admin.id, admin_path(admin) %></td>
        <td><%= admin.email %></td>
        <td><%= admin.current_sign_in_at %></td>
        <td><%= admin.last_sign_in_at %></td>
	<td><%= admin.created_at %></td>
        <td></td>
        
       
        <td>
		
 		
		<%= link_to  t('.edit', :default => t("Перегляд")),
                      admin_path(admin), :class => 'btn btn-mini', :style=>'background:#00C322' %>
		<%= link_to  t('.edit', :default => t("Редагувати")),
                      edit_admin_path(admin), :class => 'btn btn-mini', :style=>'background:#ff8940' %>
	

	    
          
        </td>
      </tr>

    <% end %>

  </tbody>

</table>

<%= link_to t('.new', :default => t("Новий користувач")), new_admin_path, :class => 'btn btn-success', :style=>"background:#3d9200" %>
</div>

app/views/admins/edit.html.erb
<%- model_class = Propose -%>
<div class="page-header">
  <h1>Користувачі Бази</h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/index.html.erb
<%- model_class = Admin -%>


<body style="background:#ffed73" >
<div   id="panel" class="span12"  style=" position:fixed;background:#ff8940;" >

 <%= render 'devise/menu/login_items' %>
<%= link_to "Повернутися на головну сторінку", :controller => "static", :action => "index" %></br>
<h6 >Користувачі бази даних</h6>

<%case current_admin.level%>
<%when 1 then%>
<%= link_to "Завантажити базу даних", :action => "download" %>

  





</div>
</br></br></br></br></br></br></br></br></br></br></br>


<div class="span12">
<table id="sort" class="table table-condensed" >
  <thead ></br></br>
<%= link_to t('.new', :default => t("Новий користувач")), new_admin_path, :class => 'btn btn-success', :style=>"background:#3d9200" %>
    <tr >
      <th>id</th>
      <th>Логін користувача</th>
	<th>Рівень користувача</th>
      <th>Дата реєстрації</th>

      <th>Дії</th>
	
    </tr>




      
  </thead>

  <tbody >
    
    <% @admins.each do |admin| %>
      <tr >


        <td><%= link_to admin.id, admin_path(admin) %></td>
        <td><%= admin.email %></td>
	<td><%= admin.level %></td>
    
	<td><%= admin.created_at %></td>
      
        
       
        <td>
		
 		
		<%= link_to  t('.edit', :default => t("Перегляд")),
                      admin_path(admin), :class => 'btn btn-mini', :style=>'background:#00C322' %>
		<%= link_to  t('.edit', :default => t("Редагувати")),
                      edit_admin_path(admin), :class => 'btn btn-mini', :style=>'background:#ff8940' %>
	

	    
          
        </td>
      </tr>

    <% end %>

  </tbody>

</table>

<%= link_to t('.new', :default => t("Новий користувач")), new_admin_path, :class => 'btn btn-success', :style=>"background:#3d9200" %>
</div>


<%else%>
<h1>У ВАС НЕДОСТАТНЬО ПРАВ ДЛЯ ПЕРЕГЛЯДУ<h1>
<%end%>



</body>

app/views/admins/new.html.erb
<%- model_class = Propose -%>
<div class="page-header">
  <h1>Оренда приватної нерухомості - Пропозиція</h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/show.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1>Користувачі</h1>
</div>

<dl class="dl-horizontal">
  <dd><strong>Логін:</strong> <%= @admin.email %></dd>
  <dd><strong>Рівень користувача:</strong> <%= @admin.level %></dd>
  <dd><strong>Час створення користувача:</strong> <%= @admin.created_at %></dd>
</dl>

<div class="form-actions", style="background:#ffed73">
  



<%= link_to t('.back', :default => t("Назад")),
              admins_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("Редагувати")),
              edit_admin_path(@admin), :class => 'btn' %>
<%= link_to t('.destroy', :default => t("Знищити")),
              admin_path(@admin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Ви впевнені?')) },
              :class => 'btn btn-danger' %>

</div>