config/routes.rb
Kursaktrue::Application.routes.draw do

  get "static/index"

  get "admins/index"

  get "admins/new"

  get "admins/show"

  get "admins/edit"
 
 get "admins/download"

  resources :private_realty_demands

  resources :private_realty_proposes

  resources :commerce_demands

  resources :commerce_proposes

  resources :demands

  resources :proposes

  root :to => 'static#index'

  devise_for :admins, :path_prefix => 'd'
  resources :admins

as :admin do
  
  get 'signin' => 'devise/sessions#new', :as => :new_admin_session
  post 'signin' => 'devise/sessions#create', :as => :admin_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session

end

end

app/models/demand.rb
class Demand < ActiveRecord::Base


def self.search(search,search1,search2)
  if search
    find(:all,
	 :conditions => ['District LIKE ? and Price LIKE ? and Count_of_rooms LIKE ? ',"%#{search}%" ,"%#{search1}%","%#{search2}%"])
  else
    find(:all)
  end
end
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
before_filter  :authenticate_admin!
require 'will_paginate/array' 

   def index

params[:min_price] = case current_admin.level
	when 1 then -1
	when 2 then 2800
	when 3 then 2400
	when 4 then -1
        else 0
end

params[:max_price] = case current_admin.level
	when 1 then 100000
	when 2 then 100000
	when 3 then 5000
	when 4 then 2800
	else 0
end

params[:statuss] = case current_admin.level
	when 1 then  params[:statuss]
	when 2 then "Актуально"
	when 3 then "Актуально"
	when 4 then "Актуально"
end
    @demandscount=Demand.search(params[:search], params[:search2], params[:min_price],params[:max_price],params[:statuss],params[:phone]).count
    @demands = Demand.search(params[:search], params[:search2], params[:min_price],params[:max_price],params[:statuss],params[:phone]).paginate(:page => params[:page], :per_page=>50)
  end


  # GET /demands/1
  # GET /demands/1.json
  def show
    @demand = Demand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @demand }
    end
  end

  # GET /demands/new
  # GET /demands/new.json
  def new
    @demand = Demand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @demand }
    end
  end

  # GET /demands/1/edit
  def edit
    @demand = Demand.find(params[:id])
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(params[:demand])

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, :notice => 'Demand was successfully created.' }
        format.json { render :json => @demand, :status => :created, :location => @demand }
      else
        format.html { render :action => "new" }
        format.json { render :json => @demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /demands/1
  # PUT /demands/1.json
  def update
    @demand = Demand.find(params[:id])

    respond_to do |format|
      if @demand.update_attributes(params[:demand])
        format.html { redirect_to @demand, :notice => 'Demand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand = Demand.find(params[:id])
    @demand.destroy

    respond_to do |format|
      format.html { redirect_to demands_url }
      format.json { head :no_content }
    end
  end
end

app/views/demands/_form.html.erb
<%= form_for @demand, :html => { :class => 'form-horizontal' } do |f| %>

<%@districts=[ "Не вказано","Галицький","Личаківський","Сихівський","Шевченківський","Залізничний","Франківський","Область"]  %>
<%@rooms=[ "Не вказано", 1, 2, 3, 4, 5, 6, 7, 8, 9]%>
<%@stages=["Не вказано",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]%>
<%@houses= ["Не вказано", "Цегла", "Панель", "Новобудова", "Особняк", "1/2 особняка", "Особн. типу", "Хрущівка", "Австрійський", "Польський", "Старий Львів", "0 цикл" ]%>
<%@heatings=["Не вказано","Центральне","Пічне","Конвекторне","Індивідуальне","Будинкове","Електричне","Без опалення"]%>
<%@furnitures=["Не вказано","Нові","Дорогі","Хай-тек","Сучасні","90-х років","Радянські","Частково","Мішані","Без меблів","Класичні","Офісні","Є"]%>
<%@conditions=["Не вказано","Євроремонт","Під євро","Санітарний","Радянський","Житловий стан","Дизайнерський","Хай-тек","Без ремонту","Нульовий цикл"]%>
<%@statuses=["Не вказано","Актуально","Не актуально"]%>

  
<dl class="dl-horizontal">

  <dt><strong>Район:</strong></dt>
  <dd><strong><%= @demand.district %></strong></dd>
  <dd><%= f.select :district, options_for_select([@demand.district]+@districts), :class=> "span2"%></dd></br>

  <dt><strong>Вулиця:</strong></dt>
  <dd><strong><%= @demand.street %></strong></dd>
  <dd><%= f.text_field :street, :class => 'text_field' %></dd>
  </br></br>

  <dt><strong>Ціна:</strong></dt>
  <dd><strong><%= @demand.price %></strong></dd>
  <dd><%= f.text_field :price, :class => 'text_field' %></dd>
  </br>  

  <dt><strong>Кількість кімнат:</strong></dt>
  <dd><strong><%= @demand.Count_of_rooms %></strong></dd>
  <dd><%= f.text_field :Count_of_rooms, :class=>'text_field'%></dd>
  </br>

 <dt><strong>Хто житиме:</strong></dt>
  <dd><strong><%= @demand.reason %></strong></dd>
    <dd><%= f.text_field :reason, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Час на пошук:</strong></dt>
  <dd><strong><%= @demand.Time_to_find %></strong></dd>
    <dd><%= f.text_field :Time_to_find, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Термін:</strong></dt>
  <dd><strong><%= @demand.Term%></strong></dd>
    <dd><%= f.text_field :Term, :class => 'text_field' %></dd>
  </br>



  <dt><strong>Клієнт:</strong></dt>
  <dd><strong><%= @demand.name %></strong></dd>
  <dd><%= f.text_field :name, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Контакти:</strong></dt>
  <dd><strong><%= @demand.phone %></strong></dd>
  <dd><%= f.text_field :phone, :class => 'text_field' %></dd>
   </br> 

<% if  @demand.Last_date.nil?%>
<% x=@demand.Last_date%>
<%else%>
<%x =@demand.Last_date.to_date%>
<%end%>
  <dt><strong>Дата:</strong></dt>
  <dd><strong><%=x%></strong></dd>
  <dd><%= f.date_select :Last_date, :class => 'date_select' %></dd>
  </br>

  <dt><strong>Статус:</strong></dt>
  <dd><strong><%=@demand.Status%></strong></dd>
  <dd><%= f.select :Status, options_for_select([@demand.Status]+@statuses), :class=> "span1"%></dd>
  </br>

  <dt><strong>Інше:</strong></dt>
  <dd><strong><%=@demand.Other%></strong></dd>  
  <dd> <%= f.text_area:Other, :class => 'text_field', :size=> '25x10' %></dd>









  <div class="form-actions", style="background:#ffed73">
    <%= f.submit  :Оновити, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("Відміна")),
                demands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<%- model_class = Demand -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/demands/index.html.erb
<%- model_class = Demand -%>
<body>
<div   id="panel" class="span12"  style=" position:fixed;background:#ff8940;" >

 <%= render 'devise/menu/login_items' %>
<%= link_to "Повернутися на головну сторінку", :controller => "static", :action => "index" %>
  <h6>Оренда приватної нерухомості - Попит</h6>
<p>Кількість позицій в базі даних - <%=@demandscount%></p>

<table class="table table-condensed">


    <tr >

      <th >Район</th>

      <th >Кількість кімнат</th>

      <th >Статус</th>
      <th>Номер телефону</th>

      <th><%=t '.actions', :default => t("Дії") %></th>

    </tr>

	 <tr>
	<%= form_tag demands_path, :method =>'get' do %>

		<td><%= select_tag "search", raw ("<option></option><option>Не вказано</option><option>Галицький</option><option>Личаківський</option><option>Сихівський</option><option>Шевченківський</option><option>Залізничний</option><option>Франківський</option><option>Область</option>"), :class=> "span1"%></td>

	<td><%= text_field_tag :search2, params[:search2], :class=> 'span1'%></td>
<%if current_admin.level!=1%>
 <td><h6>Актуально</h6></td>

 <%else%>
	<td><%= select_tag :statuss, raw ("<option></option><option>Не вказано</option><option>Актуально</option><option>Не актуально</option>"), :class=> "span1"%></td>
<% end %>


	<td><%= text_field_tag :phone, params[:phone], :class=> 'span1'%></td>
    	<td><%= submit_tag "Search", :name => nil, :class => 'btn btn-medium' %></td>

	<% end %>


      </tr>
</table>

</div>
</br></br></br></br></br></br></br></br></br></br></br>





<div class="span12">
<table class="table table-condensed">
  <thead> </br></br>
<%= link_to t('.new', :default => t("Створити")),
            new_demand_path,
            :class => 'btn btn-primary', :style=>"background:#3d9200" %>
    <tr >
      <th ><%= model_class.human_attribute_name(:id) %></th>
      <th >Район</th>
      <th class="span4">Вулиця</th>
      <th class="span4">Хто проживатиме</th>
      <th >Ціна</th>
      <th >Час на пошуки</th>
      <th >Термін оренди</th>
      <th style="text-align:center">Кількість кімнат</th>
      <th >Дата останнього дзвінка</th>
      <th >Статус</th>
      <th>Номер телефону</th>
      <th>Ім'я</th>
      <th><%=t '.actions', :default => t("Дії") %></th>

    </tr>

  </thead>
  <tbody>
    <% @demands.each do |demand| %>
      <tr>
        <td><%= link_to demand.id, demand_path(demand) %></td>
        <td><%= demand.district %></td>
        <td><%= demand.street %></td>
	<td><%= demand.reason %></td>
        <td><%= demand.price %></td>
        <td><%= demand.Time_to_find %></td>
	<td><%= demand.Term %></td>
        <td><%= demand.Count_of_rooms %></td>
        <td><%= demand.Last_date.to_date%></td>
        <td><%= demand.Status %></td>
        <td><%= demand.name %></td>
        <td></td>

        <td>
		<%if current_admin.level!=1%>
 		<%= link_to  t('.edit', :default => t("Перегляд")),
                      demand_path(demand), :class => 'btn btn-mini', :style=>'background:#00C322' %>

 		<%else%>
		<%= link_to  t('.edit', :default => t("Перегляд")),
                      demand_path(demand), :class => 'btn btn-mini', :style=>'background:#00C322' %>
		<%= link_to  t('.edit', :default => t("Редагувати")),
                      edit_demand_path(demand), :class => 'btn btn-mini' , :style=>'background:#ff8940'%>
		<% end %>

        </td>
      </tr>
    <% end %>
<tr><strong><%= will_paginate @demands%></strong></tr>
  </tbody>
<tr><strong><%= will_paginate @demands %></strong></tr>
</table>
<%= link_to t('.new', :default => t("Створити")),
            new_demand_path,
            :class => 'btn btn-primary' ,:style=>"background:#3d9200"%>
</div>

</body>

app/views/demands/new.html.erb
<%- model_class = Demand -%>
<div class="page-header">
  <h1>Оренда приватної нерухомості - Попит</h1>
</div>
<%= render :partial => 'form' %>

app/views/demands/show.html.erb
<%- model_class = Demand -%>
<div class="page-header">
  <h1>Оренда приватної нерухомості - Попит</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Район:</strong></dt>
  <dd><%= @demand.district %>;</dd>
  <dt><strong>Вулиця:</strong></dt>
  <dd><%= @demand.street %>;</dd>
  <dt><strong>Ціна:</strong></dt>
  <dd><%= @demand.price %>;</dd>
  <dt><strong>Кількість кімнат:</strong></dt>
  <dd><%= @demand.Count_of_rooms %>;</dd>
  <dt><strong>Хто житиме:</strong></dt>
  <dd><%= @demand.reason %>;</dd>
  <dt><strong>Час на пошук:</strong></dt>
  <dd><%= @demand.Time_to_find %>;</dd>
  <dt><strong>Термін оренди:</strong></dt>
  <dd><%= @demand.Term %>;</dd>
  <dt><strong>Клієнт:</strong></dt>
  <dd><%= @demand.name %>;</dd>
  <dt><strong>Контакти клієнта:</strong></dt>
  <dd><%= @demand.phone %>;</dd>
  <dt><strong>Статус:</strong></dt>
  <dd><%=@demand.Status%>;</dd>
  <dt><strong>Дата дзвінка:</strong></dt>
  <dd><%=@demand.Last_date.to_date%>;</dd>
  <dt><strong>Інше:</strong></dt>
  <dd><%=@demand.Other%>;</dd>  
</dl>

<div class="form-actions", style="background:#ffed73">
  <%if current_admin.level!=1%>
<%= link_to t('.back', :default => t("Назад")),
              demands_path, :class => 'btn'  %>
<%else%>
<%= link_to t('.back', :default => t("Назад")),
              demands_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("Редагувати")),
              edit_demand_path(@demand), :class => 'btn' %>
<%= link_to t('.destroy', :default => t("Знищити")),
              demand_path(@demand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Ви впевнені?')) },
              :class => 'btn btn-danger' %>
<%end%>

</div>