config/routes.rb
Kursaktrue::Application.routes.draw do

  get "static/index"

  get "admins/index"

  get "admins/new"

  get "admins/show"

  get "admins/edit"
 
 get "admins/download"

  resources :private_realty_demands

  resources :private_realty_proposes

  resources :commerce_demands

  resources :commerce_proposes

  resources :demands

  resources :proposes

  root :to => 'static#index'

  devise_for :admins, :path_prefix => 'd'
  resources :admins

as :admin do
  
  get 'signin' => 'devise/sessions#new', :as => :new_admin_session
  post 'signin' => 'devise/sessions#create', :as => :admin_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session

end

end

app/models/commerce_demand.rb
class CommerceDemand < ActiveRecord::Base
	  


def self.search(search,search1)
  if search
    find(:all, :conditions => ['district LIKE ? and street LIKE ?',"%#{search}%" ,"%#{search1}%"])
  else
    find(:all)
  end
end


end

app/controllers/commerce_demands_controller.rb
class CommerceDemandsController < ApplicationController
before_filter  :authenticate_admin!
require 'will_paginate/array'




  def index
    @commerce_demands_count= CommerceDemand.search(params[:search], params[:search1], params[:statuss],params[:phone]).paginate(:page => params[:page]).count
    @commerce_demands = CommerceDemand.search(params[:search], params[:search1], params[:statuss],params[:phone]).paginate(:page => params[:page], :per_page=>50)
     
  end


  def show
    @commerce_demand = CommerceDemand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @commerce_demand }
    end
  end

  # GET /commerce_demands/new
  # GET /commerce_demands/new.json
  def new
    @commerce_demand = CommerceDemand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @commerce_demand }
    end
  end

  # GET /commerce_demands/1/edit
  def edit
    @commerce_demand = CommerceDemand.find(params[:id])
  end

  # POST /commerce_demands
  # POST /commerce_demands.json
  def create
    @commerce_demand = CommerceDemand.new(params[:commerce_demand])

    respond_to do |format|
      if @commerce_demand.save
        format.html { redirect_to @commerce_demand, :notice => 'Запит успішно створено.' }
        format.json { render :json => @commerce_demand, :status => :created, :location => @commerce_demand }
      else
        format.html { render :action => "new" }
        format.json { render :json => @commerce_demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commerce_demands/1
  # PUT /commerce_demands/1.json
  def update
    @commerce_demand = CommerceDemand.find(params[:id])

    respond_to do |format|
      if @commerce_demand.update_attributes(params[:commerce_demand])
        format.html { redirect_to @commerce_demand, :notice => 'Запит успішно оновлено.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @commerce_demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commerce_demands/1
  # DELETE /commerce_demands/1.json
  def destroy
    @commerce_demand = CommerceDemand.find(params[:id])
    @commerce_demand.destroy

    respond_to do |format|
      format.html { redirect_to commerce_demands_url }
      format.json { head :no_content }
    end
  end
end

app/views/commerce_demands/_form.html.erb
<%= form_for @commerce_demand, :html => { :class => 'form-horizontal' } do |f| %>

 <%@districts=[ "Не вказано","Галицький","Личаківський","Сихівський","Шевченківський","Залізничний","Франківський","Область"]  %>
<%@rooms=[ "Не вказано", 1, 2, 3, 4, 5, 6, 7, 8, 9]%>
<%@stages=["Не вказано",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]%>
<%@houses= ["Не вказано", "Цегла", "Панель", "Новобудова", "Особняк", "1/2 особняка", "Особн. типу", "Хрущівка", "Австрійський", "Польський", "Старий Львів", "0 цикл" ]%>
<%@heatings=["Не вказано","Центральне","Пічне","Конвекторне","Індивідуальне","Будинкове","Електричне","Без опалення"]%>
<%@furnitures=["Не вказано","Нові","Дорогі","Хай-тек","Сучасні","90-х років","Радянські","Частково","Мішані","Без меблів","Класичні","Офісні","Є"]%>
<%@conditions=["Не вказано","Євроремонт","Під євро","Санітарний","Радянський","Житловий стан","Дизайнерський","Хай-тек","Без ремонту","Нульовий цикл"]%>
<%@statuses=["Не вказано","Актуально","Не актуально"]%> 



<dl class="dl-horizontal">

  <dt><strong>Район:</strong></dt>
  <dd><strong><%= @commerce_demand.district %></strong></dd>
  <dd><%= f.select :district, options_for_select([@commerce_demand.district]+@districts), :class=> "span2"%></dd></br>

  <dt><strong>Адреса:</strong></dt>
  <dd><strong><%= @commerce_demand.street %></strong></dd>
  <dd><%= f.text_field :street, :class => 'text_field' %></dd>
  </br></br>

  <dt><strong>Ціна:</strong></dt>
  <dd><strong><%= @commerce_demand.price %></strong></dd>
  <dd><%= f.text_field :price, :class => 'text_field' %></dd>
  </br>  

  <dt><strong>Площа:</strong></dt>
  <dd><strong><%= @commerce_demand.square %></strong></dd>
  <dd><%= f.text_field :square, :class => 'text_field' %></dd>
  </br>
  
  <dt><strong>Спосіб використання:</strong></dt>
  <dd><strong><%= @commerce_demand.reason %></strong></dd>
  <dd><%= f.text_field :reason, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Клієнт:</strong></dt>
  <dd><strong><%= @commerce_demand.name %></strong></dd>
  <dd><%= f.text_field :name, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Контакти:</strong></dt>
  <dd><strong><%= @commerce_demand.phone %></strong></dd>
  <dd><%= f.text_field :phone, :class => 'text_field' %></dd>
   </br> 

<% if  @commerce_demand.Last_date.nil?%>
<% x=@commerce_demand.Last_date%>
<%else%>
<%x =@commerce_demand.Last_date.to_date%>
<%end%>
  <dt><strong>Дата:</strong></dt>
  <dd><strong><%=x%></strong></dd>
  <dd><%= f.date_select :Last_date, :class => 'date_select' %></dd>
  </br>

  <dt><strong>Статус:</strong></dt>
  <dd><strong><%=@commerce_demand.Status%></strong></dd>
  <dd><%= f.select :Status, options_for_select([@commerce_demand.Status]+@statuses), :class=> "span1"%></dd>
  </br>

  <dt><strong>Інше:</strong></dt>
  <dd><strong><%=@commerce_demand.Other%></strong></dd>  
  <dd> <%= f.text_area:Other, :class => 'text_field', :size=> '25x10' %></dd>


</dl>


  <div class="form-actions", style="background:#ffed73">
    <%= f.submit :Оновити, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                commerce_demands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/commerce_demands/edit.html.erb
<%- model_class = CommerceDemand -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/commerce_demands/index.html.erb
<%- model_class = CommerceDemand -%>
<body >
<div   id="panel" class="span12"  style=" position:fixed;background:#ff8940;" >

 <%= render 'devise/menu/login_items' %>
<%= link_to "Повернутися на головну сторінку", :controller => "static", :action => "index" %>
  <h6>Комерційна нерухомість - Попит</h6>
<p>Кількість позицій в базі даних - <%=@commerce_demands_count%></p>
<table class="table table-condensed">
  

    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Район </th>
      <th>Вулиця</th>
      
      <th>Статус</th>
      
	  <th>Номер телефону</th>
      <th>Дії</th>
    </tr>
  

 <tr>
	<%= form_tag commerce_demands_path, :method =>'get' do %>
	<td></td>
		<td><%= select_tag "search", raw ("<option></option><option>Не вказано</option><option>Галицький</option><option>Личаківський</option><option>Сихівський</option><option>Шевченківський</option><option>Залізничний</option><option>Франківський</option><option>Область</option>"), :class=> "span2"%></td>
    	<td><%= text_field_tag :search1, params[:search1] %></td>
	
<%if current_admin.level!=1%>
 <td><h6>Актуально</h6></td>

 <%else%>
	<td><%= select_tag :statuss, raw ("<option></option><option>Не вказано</option><option>Актуально</option><option>Не актуально</option>"), :class=> "span1"%></td>
<% end %>





    	<td><%= text_field_tag :phone, params[:phone], :class=> 'span1'%></td>
    	<td><%= submit_tag "Search", :name => nil, :class => 'btn btn-medium' %></td>
  	
	<% end %>


      </tr>
</table>
</div>
</br></br></br></br></br></br></br></br></br></br></br>

<div class="span12">
<table class="table table-condensed">
  <thead></br></br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_commerce_demand_path,
            :class => 'btn btn-primary', :style=>"background:#3d9200" %>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Район </th>
      <th class="span3">Вулиця</th>
      <th>Площа</th>
      <th>Ціна</th>
      <th class="span3">Спосіб використання</th>
      <th>Статус</th>
      <th>Дата останнього дзвінка<th>

      <th>Дії</th>
    </tr>
  

 
</thead>
  <tbody>
<tr></tr>
    <% @commerce_demands.each do |commerce_demand| %>
     
      <tr>
        <td><%= link_to commerce_demand.id, commerce_demand_path(commerce_demand) %></td>
        <td><%= commerce_demand.district %></td>
        <td><%= commerce_demand.street %></td>
        <td><%= commerce_demand.square %></td>
        <td><%= commerce_demand.price %></td>
        <td><%= commerce_demand.reason %></td>
	<td><%= commerce_demand.Status %></td>
	<td><%= commerce_demand.Last_date.to_date %></td><td></td>
        <td>
		<%if current_admin.level!=1%>
 		<%= link_to  t('.edit', :default => t("Перегляд")),
                      commerce_demand_path(commerce_demand), :class => 'btn btn-mini', :style=>'background:#00C322' %>

 		<%else%>
		<%= link_to  t('.edit', :default => t("Перегляд")),
                      commerce_demand_path(commerce_demand), :class => 'btn btn-mini' , :style=>'background:#00C322'%>
		<%= link_to  t('.edit', :default => t("Редагувати")),
                      edit_commerce_demand_path(commerce_demand), :class => 'btn btn-mini', :style=>'background:#ff8940' %>
		<% end %>
        </td>
      </tr>
    <% end %>
<tr><strong><%= will_paginate @commerce_demands %></strong></tr>
  </tbody>

</table>
<tr><strong><%= will_paginate @commerce_demands %></strong></tr>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_commerce_demand_path,
            :class => 'btn btn-primary' ,:style=>"background:#3d9200"%>

</div>
</body>
<script>
$(document).ready(function(){

	$(".btn-slide").click(function(){
		$("#panel").slideToggle("slow");
		$(this).toggleClass("active"); return false;
	});
	
	 
});
</script>

app/views/commerce_demands/new.html.erb
<%- model_class = CommerceDemand -%>
<div class="page-header">
  <h1>Комерційна нерухомість - Попит</h1>
</div>
<%= render :partial => 'form' %>

app/views/commerce_demands/show.html.erb
<%- model_class = CommerceDemand -%>
<div class="page-header">
  <h1>Комерційна нерухомість - Попит</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Район:</strong></dt>
  <dd><%= @commerce_demand.district %>;</dd>
  <dt><strong>Вулиця:</strong></dt>
  <dd><%= @commerce_demand.street %>;</dd>
  <dt><strong>Площа:</strong></dt>
  <dd><%= @commerce_demand.square %>;</dd>
  <dt><strong>Ціна:</strong></dt>
  <dd><%= @commerce_demand.price %>;</dd>
  <dt><strong>Спосіб використання:</strong></dt>
  <dd><%= @commerce_demand.reason %>;</dd>
 <dt><strong>Статус:</strong></dt>
  <dd><%= @commerce_demand.Status %>;</dd>
 <dt><strong>Дата дзвінка:</strong></dt>
  <dd><%= @commerce_demand.Last_date.to_date %>;</dd>
  <dt><strong>Клієнт:</strong></dt>
  <dd><%= @commerce_demand.name %>;</dd>
  <dt><strong>Контакти:</strong></dt>
  <dd><%= @commerce_demand.phone %>;</dd>
   <dt><strong>Інше:</strong></dt>
  <dd><%= @commerce_demand.Other%>;</dd>
</dl>

<div class="form-actions", style="background:#ffed73">
  <%if current_admin.level!=1%>
<%= link_to t('.back', :default => t("Назад")),
              commerce_demands_path, :class => 'btn'  %>
<%else%>
<%= link_to t('.back', :default => t("Назад")),
              commerce_demands_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("Редагувати")),
              edit_commerce_demand_path(@commerce_demand), :class => 'btn' %>
<%= link_to t('.destroy', :default => t("Знищити")),
              commerce_demand_path(@commerce_demand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Ви впевнені?')) },
              :class => 'btn btn-danger' %>
<%end%>
</div>