config/routes.rb
Kursaktrue::Application.routes.draw do

  get "static/index"

  get "admins/index"

  get "admins/new"

  get "admins/show"

  get "admins/edit"
 
 get "admins/download"

  resources :private_realty_demands

  resources :private_realty_proposes

  resources :commerce_demands

  resources :commerce_proposes

  resources :demands

  resources :proposes

  root :to => 'static#index'

  devise_for :admins, :path_prefix => 'd'
  resources :admins

as :admin do
  
  get 'signin' => 'devise/sessions#new', :as => :new_admin_session
  post 'signin' => 'devise/sessions#create', :as => :admin_session
  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session

end

end

app/models/private_realty_demand.rb
class PrivateRealtyDemand < ActiveRecord::Base
end

app/controllers/private_realty_demands_controller.rb
class PrivateRealtyDemandsController < ApplicationController

before_filter :authenticate_admin!
require 'will_paginate/array'
  # GET /private_realty_demands
  # GET /private_realty_demands.json
  def index
     @private_realty_demands_count=PrivateRealtyDemand.search(params[:search], params[:search1], params[:search2], params[:search3], params[:search4], params[:statuss],params[:phone]).count
    @private_realty_demands = PrivateRealtyDemand.search(params[:search], params[:search1], params[:search2], params[:search3], params[:search4], params[:statuss],params[:phone]).paginate(:page => params[:page], :per_page=>50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @private_realty_proposes }
    end
  end

  # GET /private_realty_demands/1
  # GET /private_realty_demands/1.json
  def show
    @private_realty_demand = PrivateRealtyDemand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @private_realty_demand }
    end
  end

  # GET /private_realty_demands/new
  # GET /private_realty_demands/new.json
  def new
    @private_realty_demand = PrivateRealtyDemand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @private_realty_demand }
    end
  end

  # GET /private_realty_demands/1/edit
  def edit
    @private_realty_demand = PrivateRealtyDemand.find(params[:id])
  end

  # POST /private_realty_demands
  # POST /private_realty_demands.json
  def create
    @private_realty_demand = PrivateRealtyDemand.new(params[:private_realty_demand])

    respond_to do |format|
      if @private_realty_demand.save
        format.html { redirect_to @private_realty_demand, :notice => 'Private realty demand was successfully created.' }
        format.json { render :json => @private_realty_demand, :status => :created, :location => @private_realty_demand }
      else
        format.html { render :action => "new" }
        format.json { render :json => @private_realty_demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /private_realty_demands/1
  # PUT /private_realty_demands/1.json
  def update
    @private_realty_demand = PrivateRealtyDemand.find(params[:id])

    respond_to do |format|
      if @private_realty_demand.update_attributes(params[:private_realty_demand])
        format.html { redirect_to @private_realty_demand, :notice => 'Private realty demand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @private_realty_demand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /private_realty_demands/1
  # DELETE /private_realty_demands/1.json
  def destroy
    @private_realty_demand = PrivateRealtyDemand.find(params[:id])
    @private_realty_demand.destroy

    respond_to do |format|
      format.html { redirect_to private_realty_demands_url }
      format.json { head :no_content }
    end
  end
end

app/views/private_realty_demands/_form.html.erb
<%= form_for @private_realty_demand, :html => { :class => 'form-horizontal' } do |f| %>
  
 <%@districts=[ "Не вказано","Галицький","Личаківський","Сихівський","Шевченківський","Залізничний","Франківський","Область"]  %>
<%@rooms=[ "Не вказано", 1, 2, 3, 4, 5, 6, 7, 8, 9]%>
<%@stages=["Не вказано",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]%>
<%@houses= ["Не вказано", "Цегла", "Панель", "Новобудова", "Особняк", "1/2 особняка", "Особн. типу", "Хрущівка", "Австрійський", "Польський", "Старий Львів", "0 цикл" ]%>
<%@heatings=["Не вказано","Центральне","Пічне","Конвекторне","Індивідуальне","Будинкове","Електричне","Без опалення"]%>
<%@furnitures=["Не вказано","Нові","Дорогі","Хай-тек","Сучасні","90-х років","Радянські","Частково","Мішані","Без меблів","Класичні","Офісні","Є"]%>
<%@conditions=["Не вказано","Євроремонт","Під євро","Санітарний","Радянський","Житловий стан","Дизайнерський","Хай-тек","Без ремонту","Нульовий цикл"]%>
<%@statuses=["Не вказано","Актуально","Не актуально"]%> 






<dl class="dl-horizontal">

  <dt><strong>Район:</strong></dt>
  <dd><strong><%= @private_realty_demand.District %></strong></dd>
  <dd><%= f.select :District, options_for_select([@private_realty_demand.District]+@districts), :class=> "span1"%></dd></br>

  <dt><strong>Адреса:</strong></dt>
  <dd><strong><%= @private_realty_demand.Street %></strong></dd>
  <dd><%= f.text_field :Street, :class => 'text_field' %></dd>
  </br></br>

  <dt><strong>Ціна:</strong></dt>
  <dd><strong><%= @private_realty_demand.Price %></strong></dd>
  <dd><%= f.text_field :Price, :class => 'text_field' %></dd>
  </br>  

  <dt><strong>Кількість кімнат:</strong></dt>
  <dd><strong><%= @private_realty_demand.Count_of_rooms %></strong></dd>
  <dd><%= f.text_field :Count_of_rooms, :class=>'text_field'%></dd>
  </br>

  
  <dt><strong>Будівля:</strong></dt>
  <dd><strong><%= @private_realty_demand.Type %></strong></dd>
  <dd><%= f.select :Type, options_for_select([@private_realty_demand.Type]+@houses), :class=> "span1"%></dd>
  </br>

  <dt><strong>Опалення:</strong></dt>
  <dd><strong><%= @private_realty_demand.Heating %></strong></dd>
  <dd><%= f.select :Heating, options_for_select([@private_realty_demand.Heating]+@heatings), :class=> "span1"%></dd>
  </br>

  <dt><strong>Площа:</strong></dt>
  <dd><strong><%= @private_realty_demand.Square %></strong></dd>
  <dd><%= f.text_field :Square, :class=> "span1"%></dd>
  </br>

  <dt><strong>Стан:</strong></dt>
  <dd><strong><%= @private_realty_demand.Condition %></strong></dd>
  <dd><%= f.select :Condition, options_for_select([@private_realty_demand.Condition]+@conditions), :class=> "span1"%></dd>
  </br>

  <dt><strong>Клієнт:</strong></dt>
  <dd><strong><%= @private_realty_demand.Buyer%></strong></dd>
  <dd><%= f.text_field :Buyer, :class => 'text_field' %></dd>
  </br>

  <dt><strong>Контакти:</strong></dt>
  <dd><strong><%= @private_realty_demand.Contacts %></strong></dd>
  <dd><%= f.text_field :Contacts, :class => 'text_field' %></dd>
   </br> 

<% if  @private_realty_demand.Last_date.nil?%>
<% x=@private_realty_demand.Last_date%>
<%else%>
<%x =@private_realty_demand.Last_date.to_date%>
<%end%>
  <dt><strong>Дата:</strong></dt>
  <dd><strong><%=x%></strong></dd>
  <dd><%= f.date_select :Last_date, :class => 'date_select' %></dd>
  </br>

  <dt><strong>Статус:</strong></dt>
  <dd><strong><%=@private_realty_demand.Status%></strong></dd>
  <dd><%= f.select :Status,options_for_select([@private_realty_demand.Status]+@statuses), :class=> "span1"%></dd>
  </br>

  <dt><strong>Інше:</strong></dt>
  <dd><strong><%=@private_realty_demand.Other%></strong></dd>  
  <dd> <%= f.text_area:Other, :class => 'text_field', :size=> '25x10' %></dd>


</dl>

<div class="form-actions", style="background:#ffed73">
    <%= f.submit :Оновити, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("Відмінити")),
                private_realty_demands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/private_realty_demands/edit.html.erb
<%- model_class = PrivateRealtyDemand -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/private_realty_demands/index.html.erb
<%- model_class = PrivateRealtyDemand -%>


<body >
<div   id="panel" class="span12"  style=" position:fixed;background:#ff8940;" >

 <%= render 'devise/menu/login_items' %>
<%= link_to "Повернутися на головну сторінку", :controller => "static", :action => "index" %>
  <h6>Продаж приватної нерухомості - Попит</h6>
<p>Кількість позицій в базі даних - <%=@private_realty_demands_count%></p>
<table class="table table-condensed">
  <thead>

    <tr>
    
      <th>Район</th>
    
      <th>Кількість кімнат</th>
      <th>Стан</th>
      
      <th>Опалення</th>
      <th>Статус</th>
  
      <th>Номер телефону</th>
      <th>Дії</th>
    </tr>

	<tr>
	<%= form_tag private_realty_demands_path, :method =>'get' do %>
	

	<td><%= select_tag "search", raw ("<option></option><option>Не вказано</option><option>Галицький</option><option>Личаківський</option><option>Сихівський</option><option>Шевченківський</option><option>Залізничний</option><option>Франківський</option><option>Область</option>"), :class=> "span1"%></td>

   <td><%= text_field_tag :search1, params[:search1], :class=> 'span1'%>

	<td><%= select_tag "search2", raw ("<option></option><option>Не вказано</option><option>Євроремонт</option><option>Під євро</option><option>Санітарний</option><option>Радянський</option><option>Житловий стан</option><option>Без ремонту</option><option>Хай-тек</option><option>Дизайнерський</option><option>Нульовий цикл</option>"), :class=> "span1"%></td>



    	<td><%= select_tag "search4", raw ("<option></option><option>Не вказано</option><option>Центральне</option><option>Будинкове</option><option>Індивідуальне</option><option>Конвекторне</option><option>Пічне</option><option>Електричне</option><option>Без опалення</option>"), :class=> "span1"%></td>
<%if current_admin.level!=1%>
 <td><h6>Актуально</h6></td>

 <%else%>
	<td><%= select_tag :statuss, raw ("<option></option><option>Не вказано</option><option>Актуально</option><option>Не актуально</option>"), :class=> "span1"%></td>
<% end %>
	<td><%= text_field_tag :phone, params[:phone], :class=> 'span1'%></td>
    	<td><%= submit_tag "Search", :name => nil, :class => 'btn btn-medium' %></td>


  	
	<% end %>
      </tr>
</table>
</div>
</br></br></br></br></br></br></br></br></br></br>
<div class="span12">
<table class="table table-condensed">
  <thead></br></br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_private_realty_demand_path,
            :class => 'btn btn-primary', :style=>"background:#3d9200" %>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Район</th>
      <th class="span4">Вулиця</th>
      <th>Ціна</th>
      <th>Кількість кімнат</th>
      <th>Стан</th>
      <th>Площа</th>
      <th>Тип будівлі</th>
      <th>Опалення</th>
      <th>Статус</th>
      <th>Дата останнього дзвінка</th>
      <th>Номер телефону</th>
      <th>Дії</th>
    </tr>

	
  </thead>
  <tbody>
    <% @private_realty_demands.each do |private_realty_demand| %>
      <tr>
        <td><%= link_to private_realty_demand.id, private_realty_demand_path(private_realty_demand) %></td>
        <td><%= private_realty_demand.District %></td>
        <td><%= private_realty_demand.Street %></td>
        <td><%= private_realty_demand.Price %></td>
        <td><%= private_realty_demand.Count_of_rooms %></td>
        <td><%= private_realty_demand.Condition %></td>
        <td><%= private_realty_demand.Square %></td>
        <td><%= private_realty_demand.Type %></td>
        <td><%= private_realty_demand.Heating %></td>
        <td><%= private_realty_demand.Status %></td>
        <td><%= private_realty_demand.Last_date.to_date %></td><td></td>
        <td>
		<%if current_admin.level!=1%>
 		<%= link_to  t('.edit', :default => t("Перегляд")),
                      private_realty_demand_path(private_realty_demand), :class => 'btn btn-mini', :style=>'background:#00C322' %>

 		<%else%>
		<%= link_to  t('.edit', :default => t("Перегляд")),
                      private_realty_demand_path(private_realty_demand), :class => 'btn btn-mini', :style=>'background:#00C322' %>
		<%= link_to  t('.edit', :default => t("Редагувати")),
                      edit_private_realty_demand_path(private_realty_demand), :class => 'btn btn-mini' , :style=>'background:#ff8940'%>
		<% end %>
     
        </td>
      </tr>
    <% end %>
<tr><strong><%= will_paginate @private_realty_demands %></strong></tr>   
  </tbody>
<tr><strong><%= will_paginate @private_realty_demands %></strong></tr>   
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_private_realty_demand_path,
            :class => 'btn btn-primary',:style=>"background:#3d9200" %>
</div>
</body>

app/views/private_realty_demands/new.html.erb
<%- model_class = PrivateRealtyDemand -%>
<div class="page-header">
  <h1>Продаж приватної нерухомості - Попит</h1>
</div>
<%= render :partial => 'form' %>

app/views/private_realty_demands/show.html.erb
<%- model_class = PrivateRealtyDemand -%>
<div class="page-header">
  <h1>Продаж приватної нерухомості - Попит</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Район:</strong></dt>
  <dd><%= @private_realty_demand.District %>;</dd>
  <dt><strong>Вулиця:</strong></dt>
  <dd><%= @private_realty_demand.Street %>;</dd>
  <dt><strong>Ціна:</strong></dt>
  <dd><%= @private_realty_demand.Price %>;</dd>
  <dt><strong>Кількість кімнат:</strong></dt>
  <dd><%= @private_realty_demand.Count_of_rooms %>;</dd>
  <dt><strong>Стан:</strong></dt>
  <dd><%= @private_realty_demand.Condition %>;</dd>
  <dt><strong>Площа:</strong></dt>
  <dd><%= @private_realty_demand.Square %>;</dd>
  <dt><strong>Тип будівлі:</strong></dt>
  <dd><%= @private_realty_demand.Type %>;</dd>
  <dt><strong>Опалення:</strong></dt>
  <dd><%= @private_realty_demand.Heating %>;</dd>
  <dt><strong>Контакти:</strong></dt>
  <dd><%= @private_realty_demand.Contacts %>;</dd>
  <dt><strong>Клієнт:</strong></dt>
  <dd><%= @private_realty_demand.Buyer %>;</dd>
  <dt><strong>Помітки:</strong></dt>
  <dd><%= @private_realty_demand.Other %>;</dd>
  <dt><strong>Статус:</strong></dt>
  <dd><%= @private_realty_demand.Status %>;</dd>
  <dt><strong>Дата дзвінка:</strong></dt>
  <dd><%= @private_realty_demand.Last_date.to_date %>;</dd>
</dl>

<div class="form-actions", style="background:#ffed73">
  <%if current_admin.level!=1%>
<%= link_to t('.back', :default => t("Назад")),
              private_realty_demands_path, :class => 'btn'  %>
<%else%>
<%= link_to t('.back', :default => t("Назад")),
              private_realty_demands_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("Редагувати")),
              edit_private_realty_demand_path(@private_realty_demand), :class => 'btn' %>
<%= link_to t('.destroy', :default => t("Знищити")),
              private_realty_demand_path(@private_realty_demand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Ви впевнені?')) },
              :class => 'btn btn-danger' %>
<%end%>
</div>